-- SELECT * FROM dealerships;

-- SELECT * FROM INVENTORY WHERE DEALERSHIP_ID = 2;

-- SELECT * FROM VEHICLES WHERE VIN_ID = 1001; 

-- SELECT D.NAME, D.ADDRESS, D.PHONE
-- FROM DEALERSHIPS D
-- JOIN INVENTORY I ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
-- WHERE I.VIN_ID = 1003;

-- SELECT D.NAME, D.ADDRESS, D.PHONE
-- FROM DEALERSHIPS AS D
-- JOIN INVENTORY AS I ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
-- JOIN VEHICLES AS V ON I.VIN_ID = V.VIN_ID
-- WHERE V.NAME = 'Honda Accord';

SELECT 
    D.NAME AS DEALERSHIP_NAME, 
    V.NAME AS VEHICLE_NAME, 
    SC.CONTRACT_ID, 
    SC.VIN_ID, 
    SC.SALE_DATE
FROM 
    DEALERSHIPS AS D
JOIN 
    INVENTORY AS I ON D.DEALERSHIP_ID = I.DEALERSHIP_ID
JOIN 
    SALES_CONTRACTS AS SC ON I.VIN_ID = SC.VIN_ID
JOIN 
    VEHICLES AS V ON SC.VIN_ID = V.VIN_ID
WHERE 
    D.NAME = 'Dealership Three' 
    AND SC.SALE_DATE BETWEEN '2023-01-01' AND '2023-12-31';
