DROP DATABASE IF EXISTS dealership_db;

CREATE DATABASE IF NOT EXISTS dealership_db;

USE dealership_db;


CREATE TABLE DEALERSHIPS(
    DEALERSHIP_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    ADDRESS VARCHAR(50),
    PHONE VARCHAR(12)
);


CREATE TABLE VEHICLES(
    VIN_ID INT PRIMARY KEY,
    SOLD VARCHAR(3)
);

CREATE TABLE INVENTORY(
    DEALERSHIP_ID INT,
    VIN_ID INT,
    PRIMARY KEY(DEALERSHIP_ID, VIN_ID),
    FOREIGN KEY(DEALERSHIP_ID) REFERENCES DEALERSHIPS(DEALERSHIP_ID),
    FOREIGN KEY(VIN_ID) REFERENCES VEHICLES(VIN_ID)
);

CREATE TABLE SALES_CONTRACTS(
    CONTRACT_ID INT AUTO_INCREMENT PRIMARY KEY,
    VIN_ID INT,
    FOREIGN KEY(VIN_ID) REFERENCES VEHICLES(VIN_ID)
);

CREATE TABLE LEASE_CONTRACTS(
    LEASE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VIN_ID INT,
    FOREIGN KEY(VIN_ID) REFERENCES VEHICLES(VIN_ID)
);

INSERT INTO DEALERSHIPS (NAME, ADDRESS, PHONE) VALUES
('Dealership One', '1234 Elm St', '555-1234'),
('Dealership Two', '5678 Oak St', '555-5678'),
('Dealership Three', '9101 Maple St', '555-9101');

INSERT INTO VEHICLES (VIN_ID, SOLD) VALUES
(1001, 'No'),
(1002, 'Yes'),
(1003, 'No'),
(1004, 'Yes'),
(1005, 'No');

-- Insert seed data into INVENTORY
INSERT INTO INVENTORY (DEALERSHIP_ID, VIN_ID) VALUES
(1, 1001),
(1, 1002),
(2, 1003),
(2, 1004),
(3, 1005);

-- Insert seed data into SALES_CONTRACTS
INSERT INTO SALES_CONTRACTS (VIN_ID) VALUES
(1002),
(1004);

-- Insert seed data into LEASE_CONTRACTS
INSERT INTO LEASE_CONTRACTS (VIN_ID) VALUES
(1001),
(1003);
